DROP SEQUENCE HIBERNATE_SEQUENCE;

DROP TABLE kunde CASCADE CONSTRAINTS PURGE;
DROP TABLE adresse CASCADE CONSTRAINTS PURGE;
DROP TABLE bestellung CASCADE CONSTRAINTS PURGE;
DROP TABLE artikel CASCADE CONSTRAINTS PURGE;
DROP TABLE position CASCADE CONSTRAINTS PURGE;
